{% set version = "3.0.1" %}

package:
  name: summa
  version: {{ version }}

source:
  git_url: https://github.com/ncar/summa.git
  git_rev: v{{ version }}
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - liblapack
    - libblas
    - netcdf-fortran
  host:
    - liblapack
    - libblas
    - netcdf-fortran
  run:
    - liblapack
    - libblas
    - netcdf-fortran
    
test:
  commands:
    - summa.exe --help
    
about:
  home: http://github.com/ncar/summa
  license:  GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: "Hydrologic modeling framework"

  description: |
    SUMMA is a hydrologic modeling framework that can be used for the
    systematic analysis of alternative model conceptualizations with
    respect to flux parameterizations, spatial configurations, and numerical
    solution techniques. It can be used to configure a wide range of
    hydrological model alternatives and we anticipate that systematic model
    analysis will help researchers and practitioners understand reasons
    for inter-model differences in model behavior.
  doc_url: http://summa.readthedocs.io/
  dev_url: https://github.com/ncar/summa

extra:
  recipe-maintainers:
    - bartnijssen
    - arbennett
